// <auto-generated />
namespace PassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_settings_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_settings_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202103040251277_update_settings_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
