// <auto-generated />
namespace PassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class statistics_update_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(statistics_update_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103050527472_statistics_update_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
